version: '3'
services:
  myapplication:
    build:
      context: ../BackEnd
      dockerfile: ./GitHubSimulator/Dockerfile
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass