version: '3'
services:
  githubsimulatorservice:
    build:
      context: ../BackEnd
      dockerfile: ./GitHubSimulator/Dockerfile
    depends_on:
      - mongo
    ports:
      - "5270:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDatabaseSettings:ConnectionString: mongodb://mongoadmin:mongoadmin@mongo/
      MongoDatabaseSettings:DatabaseName: GitHubSimulator
      MongoDatabaseSettings:IssueCollectionName: Issue
  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "27017:27017"
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongoadmin
      ME_CONFIG_BASICAUTH_PASSWORD: mongoadmin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/ 
    depends_on:
      - mongo
