name: Build Frontend
on:
  push:
    paths:
      - 'FrontEnd/GitHubSimulatorUI/**'
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: FrontEnd/GitHubSimulatorUI
        run: npm ci

      - name: Build Angular project
        working-directory: FrontEnd/GitHubSimulatorUI
        run: npm run build
