name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set date and time as a variable
      id: date_time
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

    - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

    - name: Build and push Docker image
      run: |
        TAG="${{ github.event.after }}-${{ steps.date_time.outputs.timestamp }}"
        docker build -t githubsimulatorbackend -f BackEnd/GitHubSimulator/Dockerfile ./BackEnd/GitHubSimulator
        docker tag githubsimulatorbackend veljic/githubsimulator:$TAG
        docker push veljic/githubsimulator:$TAG
